// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditMovieController from "./edit_movie_controller.js"
application.register("edit-movie", EditMovieController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import MovieCardController from "./movie_card_controller.js"
application.register("movie-card", MovieCardController)

import SearchMoviesController from "./search_movies_controller.js"
application.register("search-movies", SearchMoviesController)
